name: Deploy to EC2 Instance

on:
  push:
    branches: main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Continuously deploy to EC2 instance
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.AWS_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["sudo -u ubuntu /bin/bash -c \"cd /var/www/riftrock_backend && git pull https://${{ secrets.RIFTROCK_PAT }}@github.com/mr-robertamoah/riftrock_backend.git main && npm install && npm run build && pm2 stop all && pm2 delete all && pm2 start dist/src/main.js --name riftrock_backend --instances 1 && pm2 save\""]' \
            --comment "Deploying RicfRock backend app"
